// 20th & 18th Accra Boys' & Girls' Brigade – Junior Section 2026
// Each weekly meeting covers 4 activity areas: Spiritual, Physical, Education, Social
export const BRIGADE_JUNIOR_SEED = [
  {
    date: '2026-01-03',
    title: 'New Year School',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: true,
    section: 'junior',
    description: null,
  },
  {
    date: '2026-01-17',
    title: 'Welcome / Friendly Saturday',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: true,
    section: 'junior',
    description: null,
  },
  {
    date: '2026-01-24',
    title: 'Knowing Your Prophets (Major)',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Knowing your Prophets (Major) • Physical: Figure Marching • Education: The Church (GSMC) • Social: Scavenger Hunt',
  },
  {
    date: '2026-01-31',
    title: 'Knowing Your Prophets (Minor)',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Knowing your Prophets (Minor) • Physical: Uniform & Salute • Education: BB/GB History • Social: Tell the Time',
  },
  {
    date: '2026-02-07',
    title: 'Fruit of the Spirit – Love',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruit of Spirit (Love) • Physical: Hygiene – How to Wash Your Hands • Education: Chocolate Day (Benefits of Cocoa) • Social: Short Skit (Love)',
  },
  {
    date: '2026-02-14',
    title: 'Sharing of the Word of God',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Sharing of the word of God • Physical: Walk & Talk • Education: The Community/Chocolate • Social: Socialization amongst boys & girls',
  },
  {
    date: '2026-02-21',
    title: 'Character Study – David & Jonathan',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Character Study (David & Jonathan) • Physical: Indoor Games • Education: Designs & Patterns • Social: Thread and Needle (Fixing Buttons)',
  },
  {
    date: '2026-02-28',
    title: 'Character Study – Joseph & His Brothers',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Character Study (Joseph & Brothers) • Physical: Jumping Skills (Skipping) • Education: Knowing your Weather • Social: Self Identity',
  },
  {
    date: '2026-03-07',
    title: 'Character Study – Elijah',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Character Study (Elijah) • Physical: Figure Marching • Education: History of Ghana (Coat of Arms) • Social: Drawing, Coloring & Naming of Coat of Arms',
  },
  {
    date: '2026-03-14',
    title: 'Boyhood of Jesus (Luke 2:41-52)',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Boyhood of Jesus (Luke 2:41-52) • Physical: Kicking Skills • Education: Castles & Fortes • Social: Thread & Needle',
  },
  {
    date: '2026-03-21',
    title: 'Hymns and Meanings',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Hymns and Meanings • Physical: Kofi Says • Education: How to Save • Social: Tell the Time',
  },
  {
    date: '2026-03-28',
    title: 'Fruits of the Spirit',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruits of the Spirit • Physical: Indoor Games • Education: Knowing your Plants • Social: Gardening – Planting a Seed',
  },
  {
    date: '2026-04-04',
    title: 'Christian Festival – Death of Christ',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: true,
    section: 'junior',
    description: 'Spiritual: Christian Festival (Death of Christ) • Special: Easter Movie • Social: Q & A',
  },
  {
    date: '2026-04-11',
    title: 'Understanding Salvation',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Understanding Salvation • Physical: Scavenger Hunt • Education: Home Safety (Electricals, Fire, Sharp Objects) • Social: Cross Word Puzzle',
  },
  {
    date: '2026-04-18',
    title: 'Fruit of the Spirit – Long-Suffering',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruit of the Spirit (Long-Suffering) • Physical: Let\'s Dance • Education: Knowing your Officers • Social: Short Skit (Long Suffering)',
  },
  {
    date: '2026-04-25',
    title: 'Knowing the 12 Disciples',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Knowing the 12 Disciples • Physical: Throwing Skills • Education: Career Guidance • Social: Sword Drill',
  },
  {
    date: '2026-05-02',
    title: 'How to Pray',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: How to Pray • Physical: Weekend Routine – How to Spend Your Weekend • Education: Planning your Day • Social: Keeping a Journal',
  },
  {
    date: '2026-05-09',
    title: 'Opening the Bible',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Opening the Bible • Physical: How to Buckle Your Shoe • Education: Courtesy for Girls and Boys • Social: Sword Drill',
  },
  {
    date: '2026-05-16',
    title: 'The 10 Commandments',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: The 10 Commandments • Physical: Figure Marching • Education: Manners • Social: Friendly Day',
  },
  {
    date: '2026-05-23',
    title: 'How to Study the Bible (Morning Devotion)',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: How to Study the Bible (Morning Devotion) • Physical: Flip the Bottle • Education: Knowing your Emergency Numbers • Social: Pick & Act (Bible Character Version)',
  },
  {
    date: '2026-05-30',
    title: 'Fruits of the Spirit – Joy',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruits of the Spirit (Joy) • Physical: Uniform & Salute • Education: First Aid • Social: Share your Devotion',
  },
  {
    date: '2026-06-06',
    title: 'Books of the Bible',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Books of the Bible • Physical: Scavenger Hunt • Education: Societal Safety – How to Treat Strangers • Social: Learn a Poem',
  },
  {
    date: '2026-06-13',
    title: 'The 4 Gospels',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: The 4 Gospels • Physical: Flip the Bottle • Education: Keeping the Community Clean • Social: Knowing Me Knowing You',
  },
  {
    date: '2026-06-20',
    title: 'Fruits of the Spirit – Kindness',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruits of the Spirit (Kindness) • Physical: Musical Chairs • Education: BB History – Local • Social: Singing Hymns',
  },
  {
    date: '2026-06-27',
    title: 'Evangelism – Sharing Your Devotion',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Evangelism – Sharing your Devotion • Physical: Kick and Score • Education: Health Talk • Social: Vesper',
  },
  {
    date: '2026-08-01',
    title: 'Songs and Their Impact',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Songs and its Impact • Physical: Hawk and Hen • Education: Home Duty Assistance • Social: It Takes Two',
  },
  {
    date: '2026-08-08',
    title: "The Apostle's Creed",
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: "Spiritual: The Apostle's Creed • Physical: Aiming Skills • Education: The Church & Its Organizations • Social: Paper Craft",
  },
  {
    date: '2026-08-15',
    title: "The Apostle's Creed – Revision",
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: "Spiritual: The Apostle's Creed Revision • Physical: Sections in Brigade • Education: Keeping the Home Clean • Social: Aim, Principle / Object",
  },
  {
    date: '2026-08-22',
    title: 'Fruits of the Spirit – Self Control',
    moderator: 'Junior Brigade',
    resource_persons: null,
    venue: 'Good Shepherd Methodist Church',
    is_special: false,
    section: 'junior',
    description: 'Spiritual: Fruits of the Spirit (Self Control) • Physical: Kicking Skills • Education: Conflict Resolution • Social: Draw Your Favourite Bible Character',
  },
]
