// Good Shepherd Methodist Church Society Programme for 2026
// Theme: "Walking In The Word: Equipped For Every Good Work" – 2 Timothy 3:16-17
export const CHURCH_CALENDAR_SEED = [
  // ─── JANUARY ───────────────────────────────────────────────
  { date: '2026-01-02', title: 'New Year School', moderator: 'Brigade', resource_persons: null, venue: 'Ablekuma', is_special: true, section: null, description: null },
  { date: '2026-01-04', title: 'Covenant Sunday & Family Service', moderator: 'Circuit', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-01-05', title: 'Lay Week of Prayer & Fasting', moderator: 'Circuit', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-11', title: 'Circuit 30th Anniversary Launch', moderator: 'Circuit', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-01-12', title: 'Evangelism', moderator: 'Christ Little Band', resource_persons: null, venue: 'Bubiashie', is_special: false, section: null, description: null },
  { date: '2026-01-15', title: 'Prayer Meeting', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-17', title: 'Diocesan Prayer Retreat, Rededication & Thanksgiving Service', moderator: 'Singing Band', resource_persons: null, venue: 'TBD', is_special: true, section: null, description: null },
  { date: '2026-01-17', title: 'Rededication Service', moderator: 'Circuit Choir', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-01-17', title: 'Training', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-18', title: 'Quarterly Meeting', moderator: 'Circuit', resource_persons: null, venue: 'Good News', is_special: false, section: null, description: null },
  { date: '2026-01-19', title: 'Christ Little Band Founders Day', moderator: 'Christ Little Band', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-01-21', title: 'Prayer Session', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-22', title: 'Launch – Dunwell', moderator: 'MYF', resource_persons: null, venue: 'Dunwell', is_special: true, section: null, description: null },
  { date: '2026-01-26', title: 'Touching the Father\'s Heart', moderator: 'COEYD', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-28', title: 'Talk on Planning & Budgeting', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-01-31', title: 'Leadership Summit', moderator: 'YDM', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-01-31', title: 'Breakfast Meeting with Patrons & Patroness', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },

  // ─── FEBRUARY ──────────────────────────────────────────────
  { date: '2026-02-01', title: 'New Year Prayer Retreat', moderator: 'Brigade', resource_persons: null, venue: 'Ablekuma', is_special: true, section: null, description: null },
  { date: '2026-02-02', title: 'Prayer Meeting', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-04', title: 'Talk on Relationships', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-07', title: 'Diocesan MGF Officers Retreat', moderator: 'MGF', resource_persons: null, venue: 'Dansoman', is_special: false, section: null, description: null },
  { date: '2026-02-07', title: 'Leaders Retreat', moderator: 'Guild', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-07', title: 'Circuit Lay Council Retreat', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-02-09', title: "Children's Week Celebration", moderator: 'Circuit', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-02-11', title: 'Talk on Security Alert', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-14', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-14', title: 'Celebration of Love', moderator: 'YDM', resource_persons: null, venue: 'TBD', is_special: true, section: null, description: null },
  { date: '2026-02-18', title: 'Ash Wednesday – Lent Begins', moderator: 'COM', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-02-18', title: 'Talk on Anniversary Theme', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-18', title: 'Health Talk on Bones', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-20', title: 'All Night Prayer Service', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-02-21', title: 'Officers Retreat', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-22', title: 'Time with Uncle Ebo Whyte', moderator: 'Social Service', resource_persons: 'Uncle Ebo Whyte', venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-02-22', title: '30th Anniversary Launch', moderator: 'MYF', resource_persons: null, venue: 'Dunwell', is_special: true, section: null, description: null },
  { date: '2026-02-23', title: 'Talk', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-25', title: 'Prayer Time', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-02-28', title: 'Circuit Leaders Retreat', moderator: 'COM', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-02-28', title: 'Lay Movement Week', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },

  // ─── MARCH ─────────────────────────────────────────────────
  { date: '2026-03-04', title: 'Talk on Tithing', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-06', title: 'Vigil Night', moderator: 'MYF', resource_persons: null, venue: 'Good News', is_special: true, section: null, description: null },
  { date: '2026-03-06', title: 'Young People Leadership Retreat', moderator: 'COEYD', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-07', title: 'Friendly Friday & Indoor Games', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-09', title: 'Visitation', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-09', title: 'Lay Week Celebration', moderator: 'Lay Movement', resource_persons: null, venue: 'All Societies', is_special: false, section: null, description: null },
  { date: '2026-03-11', title: 'Bible Quiz', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-14', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-20', title: 'Circuit Conference', moderator: 'Circuit Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-21', title: 'Breakfast Meeting', moderator: 'YDM', resource_persons: null, venue: 'Dunwell', is_special: false, section: null, description: null },
  { date: '2026-03-23', title: 'Evangelism', moderator: 'YDM', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-03-23', title: 'Circuit Revival', moderator: 'Circuit', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-03-24', title: 'Visitation', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-03-25', title: 'Fundraising Musical Concert', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-03-28', title: 'Word & Hymns on the Street', moderator: 'Brigade', resource_persons: null, venue: 'TBD', is_special: true, section: null, description: null },
  { date: '2026-03-29', title: 'Ten Lessons', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-03-29', title: 'MGF Leadership Summit', moderator: 'MGF', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-03-29', title: 'Passion Week', moderator: 'COM', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-03-30', title: 'Evangelism', moderator: 'Christ Little Band', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },

  // ─── APRIL ─────────────────────────────────────────────────
  { date: '2026-04-01', title: 'Prayer Time & Teachings with Minister', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-03', title: 'Circuit Organisational Leadership Meeting', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-04-04', title: 'EasterFest', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-04-05', title: 'Easter Sunday', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-04-06', title: 'Sports Evangelism', moderator: 'COM', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-04-09', title: 'Prayer Meeting', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-12', title: 'Society Meeting', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-13', title: 'Prayer Meeting', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-15', title: 'Talk on Handling Teenagers', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-18', title: 'Memorial Service', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-04-18', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-19', title: 'Quarterly Meeting', moderator: 'Circuit', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-04-22', title: 'Expectation from Leaders', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-22', title: '2nd Diocesan Joint Meeting for Zones 1 & 2', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-04-25', title: 'All Night Prayer Service', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },

  // ─── MAY ───────────────────────────────────────────────────
  { date: '2026-05-01', title: 'Excursion', moderator: "Men's Fellowship", resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-05-01', title: 'Evangelism with MYF & MGF', moderator: 'Brigade', resource_persons: null, venue: 'North Kaneshie', is_special: false, section: null, description: null },
  { date: '2026-05-06', title: "Discussion on Women's Issues", moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-13', title: 'Visitation to Aged & Patrons', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-14', title: 'Societies Lay Council Meeting with Circuit', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-05-16', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-18', title: 'Prayer and Testimony Time', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-20', title: 'Health Talk on Kidneys', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-23', title: 'Retreat', moderator: 'Church Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-05-23', title: 'Circuit Rally', moderator: 'YDM', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-05-23', title: 'Wilderness Cry – Aburi Gardens', moderator: 'Circuit', resource_persons: null, venue: 'Aburi Gardens', is_special: true, section: null, description: null },
  { date: '2026-05-27', title: 'Prayer Marathon & Youth Revival', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-05-27', title: 'Evangelism Day', moderator: "Women's Fellowship", resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-05-29', title: 'All Night Prayer Service', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },

  // ─── JUNE ──────────────────────────────────────────────────
  { date: '2026-06-01', title: 'Prayer Meeting', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-03', title: 'Bible Teachings and Prayer Time', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-06', title: 'Leadership Summit', moderator: 'YDM', resource_persons: null, venue: 'Nungua', is_special: false, section: null, description: null },
  { date: '2026-06-08', title: 'Guild Week Celebration', moderator: 'Guild', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-06-10', title: 'Talk on Attitudes', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-10', title: 'Annual General Meeting (AGM)', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-06-11', title: 'Time with Ministers, Stewards, Patrons & Patroness', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-13', title: 'Head of State Award Scheme Expedition', moderator: 'Brigade', resource_persons: null, venue: 'TBD', is_special: true, section: null, description: null },
  { date: '2026-06-13', title: 'Seminar', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-06-17', title: 'Visitation of Ministers & Evangelists', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-17', title: 'Mid-Year Concert', moderator: 'Circuit Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-06-19', title: 'Donation to Good Shepherd School', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-06-20', title: 'Word & Hymns on the Street', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-06-20', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-22', title: 'Bible Quiz', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-22', title: 'Camp Meeting – Revival', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-06-24', title: 'Talk on Handling Loneliness', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-06-28', title: 'Camp & Anniversary Thanksgiving', moderator: 'COM', resource_persons: null, venue: 'Accra ACA', is_special: true, section: null, description: null },
  { date: '2026-06-29', title: 'Evangelism', moderator: 'Christ Little Band', resource_persons: null, venue: 'North Kaneshie', is_special: false, section: null, description: null },

  // ─── JULY ──────────────────────────────────────────────────
  { date: '2026-07-01', title: 'Excursion', moderator: 'MYF', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-07-01', title: 'Prayer Session & Bible Teachings', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-07-03', title: 'Excursion', moderator: 'YDM', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-07-04', title: 'Half Year Prayer Retreat', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-07-11', title: 'Connexional Caretakers & Officers Course', moderator: 'MGF', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-07-12', title: "Young People's Week", moderator: 'COEYD', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-07-13', title: 'Time with Patrons', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-07-15', title: 'Bible Quiz', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-07-17', title: 'All Night Prayer Service', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-07-18', title: 'Visitation & Practicals', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-07-19', title: 'Quarterly Meeting', moderator: 'Circuit', resource_persons: null, venue: 'Dunwell', is_special: false, section: null, description: null },
  { date: '2026-07-20', title: 'Anniversary Thanksgiving', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-07-25', title: 'Circuit Leaders Retreat', moderator: 'Circuit', resource_persons: null, venue: 'Class Peter', is_special: false, section: null, description: null },

  // ─── AUGUST ────────────────────────────────────────────────
  { date: '2026-08-03', title: 'Visitation', moderator: 'Christ Little Band', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-08-05', title: 'Excursion to Tourist Centre', moderator: "Women's Fellowship", resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-08-12', title: 'Talk on Giving', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-08-15', title: 'Inter-Organisation Cooking Competition', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-08-15', title: 'Retreat', moderator: 'Circuit Choir', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-08-16', title: 'Redeeming Our Heritage', moderator: 'Church Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-08-17', title: 'Bible Quiz', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-08-19', title: 'Visit to Children Service', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-08-22', title: 'Street Evangelism', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-08-23', title: 'Society Meeting', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-08-24', title: 'Suwma Week Celebration', moderator: 'SUWMA', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-08-24', title: 'Wesleyan Convocation', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-08-26', title: 'Preaching Competition', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-08-29', title: 'Excursion – All Societies', moderator: 'MGF', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-08-30', title: 'Dedication Service', moderator: 'MYF', resource_persons: null, venue: 'Class Peter', is_special: true, section: null, description: null },

  // ─── SEPTEMBER ─────────────────────────────────────────────
  { date: '2026-09-01', title: '30 Days of Prayer', moderator: 'COEYD', resource_persons: null, venue: 'Online', is_special: true, section: null, description: null },
  { date: '2026-09-02', title: 'WF Thanksgiving Day – Tree of Life', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-09-03', title: 'Diocesan Conference', moderator: 'Singing Band', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-09-09', title: 'Bible Teachings & Prayer', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-09-14', title: 'Anniversary Week', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-09-16', title: 'Abokyi Night', moderator: 'Singing Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-09-19', title: 'Homecoming', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-09-19', title: 'Excursion', moderator: 'Church Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-09-20', title: 'Handing Over of Jubilee Project', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-09-21', title: 'Circuit Revival', moderator: 'Circuit', resource_persons: null, venue: 'Good News', is_special: true, section: null, description: null },
  { date: '2026-09-23', title: 'Talk on Patience', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-09-26', title: 'School Evangelism', moderator: 'MYF', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-09-26', title: 'Word & Hymns on the Street', moderator: 'Brigade', resource_persons: null, venue: 'North Kaneshie', is_special: true, section: null, description: null },
  { date: '2026-09-26', title: 'Philanthropy Ladies', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-09-27', title: 'Anniversary Thanksgiving Service', moderator: "Men's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },

  // ─── OCTOBER ───────────────────────────────────────────────
  { date: '2026-10-03', title: 'Annual Diocesan MGF Rally', moderator: 'MGF', resource_persons: null, venue: 'Christ the King', is_special: true, section: null, description: null },
  { date: '2026-10-05', title: 'Prayer Meeting', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-10-12', title: 'Talk – Menopause and Old Age', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-10-14', title: 'Health Talk on Cancers', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-10-16', title: 'Street Evangelism', moderator: 'Circuit Choir', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-10-17', title: 'Bible Quiz', moderator: 'MGF', resource_persons: null, venue: 'Christ the King', is_special: false, section: null, description: null },
  { date: '2026-10-17', title: 'Officers Retreat', moderator: 'Brigade', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-10-18', title: 'Quarterly Meeting', moderator: 'Circuit', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-10-21', title: "Time with Men's Fellowship", moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-10-25', title: 'Anniversary Thanksgiving Service – MGF', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-10-30', title: 'All Night Prayer Service', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-10-31', title: 'Prayer Convocation', moderator: 'Guild', resource_persons: null, venue: 'Aburi', is_special: true, section: null, description: null },

  // ─── NOVEMBER ──────────────────────────────────────────────
  { date: '2026-11-02', title: 'Praise and Adoration', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-11-04', title: 'Bible Quiz Competition Final', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-11-08', title: 'MYF Anniversary Thanksgiving Service', moderator: 'MYF', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
  { date: '2026-11-09', title: 'Evangelism', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-11-11', title: 'Talk on Housekeeping', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-11-18', title: 'Health Talk', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-11-22', title: 'I Came to Say Thank You', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-11-28', title: 'Band Festival', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-11-28', title: 'Time with Senior Citizens', moderator: 'Lay Movement', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-11-29', title: 'Society Meeting', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },

  // ─── DECEMBER ──────────────────────────────────────────────
  { date: '2026-12-02', title: 'Visit to Aged Members & Patrons', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-12-04', title: 'Dinner & Awards Night', moderator: 'MYF', resource_persons: null, venue: 'TBD', is_special: true, section: null, description: null },
  { date: '2026-12-05', title: 'Dramafest', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-06', title: 'Climax & Thanksgiving Service', moderator: 'MYF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-07', title: 'Lyrics Competition', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-07', title: 'Circuit Breakfast Meeting', moderator: 'COM', resource_persons: null, venue: 'TBD', is_special: false, section: null, description: null },
  { date: '2026-12-09', title: 'Visit to Ministers & Evangelists', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-12-11', title: 'Pre-Christmas Concert', moderator: 'Circuit Choir', resource_persons: null, venue: 'Dunwell', is_special: true, section: null, description: null },
  { date: '2026-12-13', title: 'Enrollment Service', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-14', title: 'Visit to Ministers & Infirm Members', moderator: 'Christ Little Band', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: false, section: null, description: null },
  { date: '2026-12-16', title: 'End of Year Get Together', moderator: "Women's Fellowship", resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-19', title: 'Nine Lessons & Chorus Service – End of Year and Evaluation', moderator: 'MGF', resource_persons: null, venue: 'Good News', is_special: true, section: null, description: null },
  { date: '2026-12-20', title: 'Carols Service', moderator: 'Church Choir', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-26', title: 'Akwaaba Fest', moderator: 'COEYD', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-26', title: 'Aseda Kese 2026', moderator: 'Brigade', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-27', title: 'Time with Queens & Fashion Swaps', moderator: 'MGF', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-28', title: 'Revival – Days Before Watchnight', moderator: 'COM', resource_persons: null, venue: 'Good Shepherd Methodist Church', is_special: true, section: null, description: null },
  { date: '2026-12-31', title: 'Watchnight Service', moderator: 'Circuit', resource_persons: null, venue: 'All Societies', is_special: true, section: null, description: null },
]
