// All 2026 MYF events parsed from the programme of activities
export const EVENTS_SEED = [
  {
    date: '2026-02-02',
    title: 'Exposition of Theme',
    moderator: 'Dagadu',
    resource_persons: 'Rev. Ernest Quayson',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-02-16',
    title: 'Relationship Talk',
    moderator: 'Dagadu',
    resource_persons: "Bro. Joseph Acquah, Sister Pat Otoo's Sister",
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-02-23',
    title: 'Focus on Lent',
    moderator: 'Dagadu',
    resource_persons: 'Bro. Robert Acquah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-03-02',
    title: 'Prayer Meeting on Lent',
    moderator: 'Wesley',
    resource_persons: 'Bro. Robert Acquah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-03-16',
    title: 'What a Young Person Should Consider in Land Ownership',
    moderator: 'Wesley',
    resource_persons: 'Dr. Odame Larbi',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-03-28',
    title: 'Aerobics',
    moderator: 'Wesley',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-03-30',
    title: 'Bible Study / Open Forum (1st Quarter Review)',
    moderator: 'Wesley',
    resource_persons: 'Bro. Robert Mensah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-04-13',
    title: 'Inter-Group Quiz on Lent',
    moderator: 'Clegg',
    resource_persons: 'Bro. Derek Ofori Akyea, Bro. Robert Acquah, Bro. John Nyarko',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-04-20',
    title: 'Financial Literacy Talk',
    moderator: 'Clegg',
    resource_persons: 'Bro. Foster Gordon, Bro. John Nyarko, Bro. Stephen Amoako',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-04-27',
    title: 'Indoor Games',
    moderator: 'Clegg',
    resource_persons: 'Bro. Herbert Ofosu Duah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-05-04',
    title: 'Atmosphere of Worship',
    moderator: 'Kitoe',
    resource_persons: 'Shepherd Voices, Sis. Francisca Kwakye, Bro. Yaw Subiri',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-05-11',
    title: 'Group Bible Studies',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Mark Quaye',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-05-18',
    title: 'Do You Know Your Group?',
    moderator: 'Kitoe',
    resource_persons: 'Group Leaders',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-05-25',
    title: 'Indoor Bible Games',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Robert Mensah, Sis. Francisca Kwakye',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-06-01',
    title: 'Prayer Meeting',
    moderator: 'Clegg',
    resource_persons: 'Bro. Nicholas Ohene',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-06-15',
    title: 'Movie Night',
    moderator: 'Clegg',
    resource_persons: 'Bro. Kofi Baah Jnr, Sis. Francisca Kwakye',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-06-20',
    title: 'Aerobics',
    moderator: 'Clegg',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-06-22',
    title: 'Karaoke Night',
    moderator: 'Clegg',
    resource_persons: 'Sis. Francisca Kwakye',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-06-29',
    title: "Time with the Minister's Wife",
    moderator: 'Clegg',
    resource_persons: 'Sis. Abena Boakyewaa Mintah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-07-06',
    title: 'Knowing the Coordinating Office of YDM',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Derek Ofori Akyea',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-07-13',
    title: "Young People's Week Celebration",
    moderator: 'Kitoe',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-07-20',
    title: "Open Forum – Assessing Young People's Week",
    moderator: 'Kitoe',
    resource_persons: 'Bro. James Sackitey',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-07-27',
    title: 'Talk on Tithing',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Foster Gordon',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-08-03',
    title: 'Prayer Meeting (Seed Sowing)',
    moderator: 'Dagadu',
    resource_persons: 'Evangelist Richmond Benuah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-08-10',
    title: 'Time with SYC / CYC',
    moderator: 'Dagadu',
    resource_persons: 'Bro. James Sackitey, Bro. Derek Ofori Akyea, Bro. Paul',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-08-17',
    title: 'Find Your Identity in Christ',
    moderator: 'Dagadu',
    resource_persons: 'Rev. Ernest Quayson',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-08-29',
    title: 'Cooking Competition',
    moderator: 'Dagadu',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-08-31',
    title: 'Ladies on the Pulpit',
    moderator: 'Dagadu',
    resource_persons: 'Sis. Vera Aduafo',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-09-07',
    title: 'Capacity Drive Awareness',
    moderator: 'Wesley',
    resource_persons: 'Maame Esi Bessah, Bro. Herbert Ofosu Duah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-09-12',
    title: 'Aerobics',
    moderator: 'Wesley',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-09-14',
    title: 'Prayer Meeting',
    moderator: 'Wesley',
    resource_persons: 'Bro. Emele Arthur Hayford',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-09-22',
    title: 'Excursion',
    moderator: 'Wesley',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-09-28',
    title: 'Learn a Skill (Vocational Skills)',
    moderator: 'Wesley',
    resource_persons: 'Sis. Portia, Sis. Perpetual, Bro. Thomas Larbi',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-10-05',
    title: 'Chinese Sales',
    moderator: 'Kitoe',
    resource_persons: 'Sis. Loretta Debrah Derby, Bro. Thomas Larbi',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-10-12',
    title: 'Wisdom Nuggets with Old Guards',
    moderator: 'Kitoe',
    resource_persons: 'Sis. NanaEsi Cobbah, Sis. Audrey Smith Dadzie',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-10-19',
    title: 'Indoor Games (with Church Leaders)',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Herbert Ofosu Duah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-10-26',
    title: 'Prayer Meeting',
    moderator: 'Kitoe',
    resource_persons: 'Bro. Khiram, Bro. Enoch Idun',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-11-02',
    title: 'Career Guidance',
    moderator: 'Dagadu',
    resource_persons: 'Bro. Foster Gordon, Sis. Florence Amissah, Dr. Bessah, Dr. Ngissah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-11-09',
    title: 'Debate',
    moderator: 'Dagadu',
    resource_persons: 'Bro. Derek Ofori Akyea, Bro. John Nyarko, Sis. Adjoa Aidoo',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-11-16',
    title: 'How to Maintain Bible Principles in Relationships',
    moderator: 'Dagadu',
    resource_persons: 'Bro. John Nyarko, Bro. Kwaku Kyei, Sis. Portia Kyei',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-11-21',
    title: 'Aerobics',
    moderator: 'Dagadu',
    resource_persons: null,
    venue: 'Church hall',
    is_special: true,
  },
  {
    date: '2026-11-23',
    title: 'Atmosphere of Praise (Approval of Funds)',
    moderator: 'Dagadu',
    resource_persons: 'Shepherd Voices',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-11-30',
    title: 'Open Forum',
    moderator: 'Dagadu',
    resource_persons: 'Bro. Robert Mensah',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-12-07',
    title: 'Talk on Practicing Self-Love / Self-Care',
    moderator: 'Clegg',
    resource_persons: 'Sis. Pat Otoo, Sis. Priscilla Agyen',
    venue: 'Church hall',
    is_special: false,
  },
  {
    date: '2026-12-14',
    title: 'Love Feast',
    moderator: 'Clegg',
    resource_persons: 'All Executives',
    venue: 'Church hall',
    is_special: true,
  },
]
